export const config = {
  user: {
    minBirthYear: 1970,
    maxBirthYear: 2003,
    isAdminProbability: 0.25,
    isVerifiedProbability: 0.95,
    gender: ["Female", "Male"],
    language: ["Vietnamese", "English"],
    designation: [
      "VP Of Operation",
      "Senior Software Engineer",
      "Software Engineer",
      "Senior QA Manager",
      "QA/Project Manager",
      "Quality Architect",
      "QA Lead",
      "Quality Analyst",
      "Technical Architect",
      "Engineering Manager",
      "Accout Manager",
      "Developer",
      "CTO",
    ],
    status: ["Active", "Inactive"],
  },
  testcase: {
    priority: ["Low", "Medium", "High", "Critical"],
  },
  bug: {
    category: ["Bug", "Task", "Subtask"],
    status: [
      "Assigned",
      "Closed",
      "Deferred",
      "Duplicate",
      "Fixed",
      "Invalid",
      "New",
      "Open",
      "Reopen",
      "Retest",
      "Verified",
    ],
    priority: ["Low", "Medium", "High", "Show stopper"],
    type: [
      "Not Applicable",
      "UI/Design",
      "Performance",
      "Validations",
      "Functionality",
      "SEO",
      "Console Error",
      "Server Error",
      "Tracking",
    ],
    environment: ["QA", "Staging", "Development", "Production", "UAT"],
    severity: ["Critical", "Blocker", "Major", "Minor", "Trivial"],
  },
} as const;
